# WebUtil.ps1 IS REQUIRED FOR ALL SCRIPTS THAT RUN IN PSWEB
# WebUtil.ps1 CONATINS VARIOUS WRITE-IN AND WRITE-OUT FUNCTIONS THAT COMMUNICATE WITH THE PSWEB APPLICATION.
. "$env:PSConsole\powershell\WebUtil.ps1"

# PARAMETERS CAN BE DEFINED AS NUMBERS, STRINGS OR AN ARRAY OF NUMBER AND STRINGS
# YOU CAN ALSO CREATE COMPLEX JSON OBJECT PARAMETERS, ANY JSON THAT CAN BE CONVERTED BY THE CONVERTFROM-JSON POWERSHELL COMMAND CAN BE PASSED IN.
write-in @"
{
    "numberIn": 0,
    "stringIn": "test",
    "narrayIn": [1,2,3,4,5],
    "sarrayIn": ["str1","str2","str3"]
}
"@

# THE PARAMETERS ARE PASSED INTO POWERSHELL USING VARIABLE: $postData
# NORMALLY THIS VARIABLE WOULD NOT BE USED. EACH PROPERTY AT THE ROOT LEVEL 
# OF THIS OBJECT IS AUTOMATICALLY TURNED INTO A POWERSHELL VARIABLE AT RUNTIME
write-out $postData "postData1"

# WRITE VARIABLES OUT TO THE WEB PAGE, NAMING THE OUTPUT VARIABLE IS OPTIONAL
# THE FIRST PARAMETER OF WRITE-OUT IS THE OBJECT TO OUTPUT
# THE SECOND PARAMETER IS THE OPTIONAL NAME OF THE OBJECT, THE NAME IS INCLUDED IN THE RESULTING JSON RESPONSE FOR REFERENCE BY THE CLIENT
write-out $numberIn "numberIn1"
write-out $stringIn "stringIn1"
write-out $narrayIn "narrayIn1"
write-out $sarrayIn "sarrayIn1"

# THE WRITE-OUT FUNCTION OUTPUTS BOTH THE JSON RESULT AND TEXT RESPONSE OF THE POWERSHELL COMMAND
# YOU CAN USE THE FOLLOWING COMMANDS TO OUTPUT ONLY THE FORMAT DESIRED IN THE RESPONSE
write-out-json $numberIn "numberIn2 json only"
write-out-outstring $stringIn "stringIn2 outstring only"
write-out-json $narrayIn "narrayIn2 json only"
write-out-outstring $sarrayIn "sarrayIn2 outstring only"
